//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationRegistryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocStage()
        {
            this.User_Stage = new HashSet<User_Stage>();
        }
    
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public int WorkTypeId { get; set; }
        public Nullable<int> OriginalId { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual WorkType WorkType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Stage> User_Stage { get; set; }
        public virtual DocFile Original { get; set; }
        public virtual DocFile Result { get; set; }
    }
}
