//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationRegistryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Stages = new HashSet<DocStage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public int WordsNumber { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int OriginalFileId { get; set; }
        public Nullable<int> FinalFileId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocStage> Stages { get; set; }
        public virtual DocFile OriginalFile { get; set; }
        public virtual DocFile FinalFile { get; set; }
    }
}
