//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationRegistryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Stages = new HashSet<Stage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public int WordsNumber { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int OriginalFileId { get; set; }
        public int FinalFileId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual File OriginalFile { get; set; }
        public virtual File FinalFile { get; set; }
    }
}
