//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationRegistryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Documents = new HashSet<Document>();
            this.Workers = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int WordsNumber { get; set; }
        public string Customer { get; set; }
        public Nullable<int> LanguagePairId { get; set; }
        public Nullable<int> ProjectStatuseId { get; set; }
        public int CreatorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual LanguagePair LanguagePair { get; set; }
        public virtual ProjectStatus ProjectStatus { get; set; }
        public virtual User Creator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Workers { get; set; }
    }
}
