//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationRegistryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Customer { get; set; }
        public Nullable<int> LanguagePairId { get; set; }
        public Nullable<int> ProjectStatuseId { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> WorkTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual LanguagePair LanguagePair { get; set; }
        public virtual ProjectStatus ProjectStatus { get; set; }
        public virtual User Creator { get; set; }
        public virtual WorkType InitialStage { get; set; }
    }
}
