//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationRegistryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Stage
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public int StageId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> DocFileId { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
    
        public virtual DocStage Stage { get; set; }
        public virtual User User { get; set; }
        public virtual DocFile DocFile { get; set; }
    }
}
